#!/usr/bin/env bash


pre() {
systemctl stop sdboot-snaps-watch.path && sleep 1
}

post() {
systemctl start sdboot-snaps-watch.path
}

case "${1:-}" in
    pre)
        pre
        ;;
    post)
        post
        ;;
esac
