#!/usr/bin/env bash

## Stop/start sdboot-snaps-watch.path during pacman transactions

pre() {
systemctl stop sdboot-snaps-watch.path && sleep 2
}

post() {
systemctl start sdboot-snaps-watch.path && sleep 2
}

case "${1:-}" in
    pre)
        pre
        ;;
    post)
        post
        ;;
esac
