#!/usr/bin/env bash

####################
#  CHECK FOR ROOT  #
####################

#if [ "$(id -u)" -ne 0 ]; then echo " $red Please run as root.$clr ex. sudo rollback" >&2; exit; fi
##########################################################

if [ -x "$(command -v xmllint)" ]; then
xmllint --xpath 'string(/snapshot)' /.snapshots/*/info.xml | tac | more
fi

if  [ "$?" -eq 1 ] & ! [ -x "$(command -v xmllint)" ]; then
grep -E ' <date>|<type>|<description>' /.snapshots/*/info.xml | awk -F '</[^}]*>' '{print $1 $2}' | sed 's/[i][^:]*//' | sed 's/[/][^s]*//' | sed 's/[<][^>>]*//' | tac | more
fi

